# Generated by Django 2.2 on 2019-08-28 09:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_feed_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
