# Generated by Django 2.2 on 2019-09-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190913_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='raw_username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
